all:
  children:
      jenkins:
        children:
          controller:
            hosts:
              controller1:
                ansible_host: "192.168.0.35"
                ansible_user: "administrator"
                ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
                platform_environment: '{{ platform_environment }}'
      artifacts:
        children:
          manager:
            hosts:
              artifacts1:
                ansible_host: "192.168.0.132"
                ansible_user: "administrator"
                ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
                platform_environment: '{{ platform_environment }}'
  