---
- name: Allow run sudo commands without password
  community.general.sudoers:
    name: admin_role
    state: present
    user: "{{ admin_user }}"
    commands: ALL

- name: Install Java (Jenkins dependency)
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download Jenkins repository key
  ansible.builtin.command:
    cmd: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key -o /tmp/jenkins-keyring.gpg"
  register: result

- name: Add Jenkins repository key
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg /tmp/jenkins-keyring.gpg"
  register: result

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Update APT cache after adding Jenkins repository
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled
  systemd:
    name: jenkins
    enabled: yes
    state: started