---
plugin_names:
- ant
- antisamy-markup-formatter
- apache-httpcomponents-client-4-api
- asm-api
- bootstrap5-api
- bouncycastle-api
- branch-api
- build-timeout
- caffeine-api
- checks-api
- cloudbees-folder
- commons-lang3-api
- commons-text-api
- credentials-binding
- credentials
- dark-theme
- display-url-api
- durable-task
- echarts-api
- eddsa-api
- email-ext
- font-awesome-api
- git-client
- git
- github-api
- github-branch-source
- github
- gradle
- gson-api
- instance-identity
- ionicons-api
- jackson2-api
- jakarta-activation-api
- jakarta-mail-api
- javax-activation-api
- javax-mail-api
- jaxb
- jjwt-api
- joda-time-api
- jquery3-api
- json-api
- json-path-api
- junit
- ldap
- mailer
- matrix-auth
- matrix-project
- metrics
- mina-sshd-api-common
- mina-sshd-api-core
- okhttp-api
- pam-auth
- pipeline-build-step
- pipeline-github-lib
- pipeline-graph-analysis
- pipeline-graph-view
- pipeline-groovy-lib
- pipeline-input-step
- pipeline-milestone-step
- pipeline-model-api
- pipeline-model-definition
- pipeline-model-extensions
- pipeline-stage-step
- pipeline-stage-tags-metadata
- plain-credentials
- plugin-util-api
- resource-disposer
- scm-api
- script-security
- snakeyaml-api
- ssh-credentials
- ssh-slaves
- ssh-agent
- structs
- theme-manager
- timestamper
- token-macro
- trilead-api
- variant
- workflow-aggregator
- workflow-api
- workflow-basic-steps
- workflow-cps
- workflow-durable-task-step
- workflow-job
- workflow-multibranch
- workflow-scm-step
- workflow-step-api
- workflow-support
- ws-cleanup
jenkins_url: "http://{{ controller_ip }}:8080"
github_username: "{{ git_user }}"
github_token: "{{ git_token }}"
proxmox_username: "{{ proxmox_token_id }}"
proxmox_token: "{{ proxmox_token_secret }}"
admin_key_location: "{{ ssh_admin_key_path }}"
tofu_sa_token: "{{ hostvars['artifacts1'].secretid | default('changeme') }}"