---
- name: Create agent policy
  ansible.builtin.template:
    src: "templates/statefiles-policy.hcl.j2"
    dest: "/tmp/statefiles-policy.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0644'

- name: Read statefiles policy file content
  slurp:
    src: "/tmp/statefiles-policy.hcl"
  register: statefiles_policy_content

- name: Create policy for statefiles path
  uri:
    url: "http://localhost:8500/v1/acl/policy"
    method: PUT
    body: "{{ statefiles_policy_content.content | b64decode }}"
    body_format: json
  register: statefiles_polic
  when: not bootstrapped_file.stat.exists

- name: Create service account token
  uri:
    url: "http://localhost:8500/v1/acl/token"
    method: PUT
    headers:
      X-Consul-Token: "{{ acl_master_token }}"
    body: |
      {
        "Description": "Service account for accessing statefiles",
        "Policies": [
          {
            "ID": "{{ statefiles_policy.json.ID }}"
          }
        ]
      }
    body_format: json
  register: service_account_token
  when: not bootstrapped_file.stat.exists

- name: Save service account token to local file
  delegate_to: localhost
  ansible.builtin.copy:
    content: "Service account token: {{ service_account_token.json.SecretID }}"
    dest: "service_account_token.txt"
  when: not bootstrapped_file.stat.exists