---
- name: Including consul installation tasks
  ansible.builtin.include_tasks:
    file: consul-installation.yaml

- name: Including basic consul configuration tasks
  ansible.builtin.include_tasks:
    file: consul-configuration.yaml

- name: Wait for Consul to be available
  uri:
    url: "http://localhost:8500/v1/status/leader"
    method: GET
    status_code: 200
  register: consul_status
  until: consul_status.status == 200
  retries: 10
  delay: 5

- name: Including acls; consul configuration tasks
  ansible.builtin.include_tasks:
    file: consul-acl.yaml

# - name: Create bootstrapped file
#   ansible.builtin.file:
#     path: "{{ ansible_user_dir }}/bootstrapped"
#     state: touch
#   when: not bootstrapped_file.stat.exists