---
- name: Install openTofu
  ansible.builtin.get_url:
    url: "https://get.opentofu.org/install-opentofu.sh"
    dest: "/tmp/install-opentofu.sh"
    mode: '0755'

- name: Run the bash script
  ansible.builtin.command: "/tmp/install-opentofu.sh --install-method deb"
  args:
    creates: "/tmp/script/output"

- name: Copy Groovy script to create pipeline job
  ansible.builtin.template:
    src: templates/create-pipeline-job.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/create-pipeline-job.groovy
    owner: jenkins
    group: jenkins
    mode: 0644
  notify:
    - Restart Jenkins