---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Update and upgrade APT packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Check for bootstrapped file
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/bootstrapped"
      register: bootstrapped_file

    - name: Install Docker
      ansible.builtin.apt:
        name: 
          - docker.io
          - docker-compose
          - gpg
          - git
        state: present
      when: not bootstrapped_file.stat.exists

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: not bootstrapped_file.stat.exists

- hosts: artifacts
  become: true
  roles:
    - role: consul

- hosts: jenkins
  become: true
  roles:
    - role: jenkins-controller

- hosts: jenkins
  become: true
  roles:
    - role: jenkins-agent