---
- name: Install openTofu
  ansible.builtin.get_url:
    url: "https://get.opentofu.org/install-opentofu.sh"
    dest: "/tmp/install-opentofu.sh"
    mode: '0755'

- name: Run the bash script
  ansible.builtin.command: "/tmp/install-opentofu.sh --install-method deb"
  args:
    creates: "/tmp/script/output-opentofu"

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Set distribution codename fact
  set_fact:
    distro_codename: "{{ ansible_distribution_release }}"

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ distro_codename }} main"
    state: present

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install Packer
  apt:
    name: packer
    state: latest

- name: Verify Packer installation
  command: packer version
  register: packer_version_output

- name: Display Packer version
  debug:
    msg: "Packer version installed: {{ packer_version_output.stdout }}"

- name: Copy Groovy script to create base image pipeline job
  ansible.builtin.template:
    src: templates/create-base-pipelines.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/create-base-pipelines.groovy
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy Groovy script to create php pipeline job
  ansible.builtin.template:
    src: templates/create-php-pipeline-job.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/create-php-pipeline-job.groovy
    owner: jenkins
    group: jenkins
    mode: 0644
  notify:
    - Restart Jenkins