---
- name: Allow run sudo commands without password
  community.general.sudoers:
    name: admin_role
    state: present
    user: "{{ admin_user }}"
    commands: ALL
  when: not bootstrapped_file.stat.exists

- name: Install OpenJDK 21
  ansible.builtin.apt:
    name: openjdk-21-jdk
    state: present
  when: not bootstrapped_file.stat.exists

- name: Download Jenkins repository key
  ansible.builtin.command:
    cmd: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key -o /tmp/jenkins-keyring.gpg"
  register: result
  when: not bootstrapped_file.stat.exists

- name: Add Jenkins repository key
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg /tmp/jenkins-keyring.gpg"
  register: result
  when: not bootstrapped_file.stat.exists

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/'
    state: present
  when: not bootstrapped_file.stat.exists

- name: Update APT cache after adding Jenkins repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
  when: not bootstrapped_file.stat.exists

- name: Ensure Jenkins is started and enabled
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
    state: started
  when: not bootstrapped_file.stat.exists

- name: Create init.groovy.d directory
  ansible.builtin.file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  when: not bootstrapped_file.stat.exists

- name: Copy Groovy script template to skip setup wizard and install plugins
  ansible.builtin.template:
    src: templates/basic-setup.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/basic-setup.groovy
    owner: jenkins
    group: jenkins
    mode: 0644
  notify:
    - Restart Jenkins
  when: not bootstrapped_file.stat.exists

- name: Copy Groovy script to add GitHub credentials
  ansible.builtin.template:
    src: templates/add-github-credential.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/add-github-credential.groovy
    owner: jenkins
    group: jenkins
    mode: 0644
  notify:
    - Restart Jenkins
  when: not bootstrapped_file.stat.exists


- name: Main restart
  ansible.builtin.service:
    name: jenkins
    state: restarted
  when: not bootstrapped_file.stat.exists

- name: Create bootstrapped file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/bootstrapped"
    state: touch
  when: not bootstrapped_file.stat.exists